### ISSUE TITLE
db hints

### ISSUE THREAD

**Issue by vitaly-t** [aries-data/aries-activity-postgres#1]
```js
}).then((data) => { // seems to never get called until stream is fully read
```
that's by design (see the [API](http://vitaly-t.github.io/pg-promise/Database.html#.stream)); and you should always provide a `.catch` section ;)

>var db = pgp(config); // create/connect to the database

It neither creates no connects to the database, just a declaration. You can take it out to the global/shared declarations, see the following to understand it better: http://stackoverflow.com/questions/36120435/verify-database-connection-with-pg-promise-when-starting-an-app

**Comment by schnie** [comment]
@vitaly-t, wow thanks for taking the time to comment here.  Since we have you here, is there a way to return a stream from a query?  The only mention of the word stream is down in the history section where it says `1.8.0 added support for Query Streaming via node-pg-query-stream.`.  Can we use this directly through `pg-promise`?

**Comment by vitaly-t** [comment]
But that's what your code is doing already :)

**Comment by schnie** [comment]
I wasn't sure if there was some way to get a stream without actually using the `pg-query-stream` package directly.  I see now that you made it compatible with `pg-query-stream`, rather than packing it up into `pg-promise`.  Thanks!  By the way, how were you alerted that we were using your package?

**Comment by vitaly-t** [comment]
>how were you alerted that we were using your package?

GitHub search engine shows recent entries against the library ;)

**Comment by schnie** [comment]
Thanks for the tips!
